lr0: 0.0004
lrf: 1.0
momentum: 0.9
weight_decay: 0.0001
# 5200 images / batch 16 = 325 steps/epoch; 1000 / 325 = 3.0769230769 epochs.
warmup_epochs: 3.076923076923077
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 0.05
cls: 0.5
cls_pw: 1.0
obj: 1.0
obj_pw: 1.0
iou_t: 0.20
anchor_t: 4.0
fl_gamma: 0.0
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
mosaic: 0.5
mixup: 0.5
copy_paste: 0.0
